### PR TITLE
Switch to MSAL 1.29+'s TokenCache.search()

### PR DESCRIPTION
**Pull request by rayluo**
This PR will only work when [this MSAL PR](https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/693) is merged and shipped (possibly in version 1.29).

CC @jiasli

### CODE REVIEW

**Review by jiasli — APPROVED** [review]

**Comment by musicinmybrain** [comment]
MSAL 1.29 has shipped, with the necessary PR.

**Comment by musicinmybrain** [comment]
Note that the [release notes](https://github.com/AzureAD/microsoft-authentication-library-for-python/releases/tag/1.29.0) say that `TokenCache.search()` returns a generator, while a compatibility `TokenCache.find()` (not `TokenCache._find()`!) returns a list and produces a `DeprecationWarning`.

**Comment by rayluo** [comment]
@musicinmybrain , you have sharp eyes to notice that MSAL 1.29 was released just hours ago!

Don't worry. We are also shipping the MSAL Extensions 1.2.0 soon.

**Comment by rayluo** [comment]
Releasing...

**Comment by jiasli** [comment]
I saw this PR got superseded by https://github.com/AzureAD/microsoft-authentication-extensions-for-python/commit/6fd4920f20ab36263a55ad228c432265f8d2f2eb.

Just a kind reminder that it is better to make the `_find` -> `search` change and version bump in separate PRs. Consider you need to revert this `_find` -> `search` change but not the version bump. Separate PRs can be handy in such situation.

**Pull request closed without merging**
